#! /bin/sh

# where --- shell file to determine what kind of environment we are in

if test -r /bin/universe	# on a pyramid
then
	OPATH=$PATH
	PATH=/bin
	case `universe` in	# universe is dumb, looking only at argv[0]
	att)	echo "-DUSG -UBSD -UBSD4_2"
		if grep LOBLK /usr/include/sys/termio.h > /dev/null
		then
			echo -DS5R2
		else
			echo -US5R2
		fi
		;;

	ucb)	echo "-UUSG -DBSD -DBSD4_2 -US5R2"
		;;

	*)	echo unknown operating system! 1>&2
		echo "-UUSG -UBSD -UBSD4_2"	# undefine them all
		echo "-US5R2"
		;;
	esac
	PATH=$OPATH
	echo -UGITVAX	# pyramid is never GITVAX
else		# on something that is not a pyrmaid
	if grep SIGTSTP /usr/include/signal.h > /dev/null
	then		# berkeley unix
		if test -r /usr/include/whoami.h	# 4.1
		then
			echo "-UUSG -DBSD -UBSD4_2"
			host="`sed 's/[^\"]*\"\([^\"]*\)\"/\1/' < /usr/include/whoami.h`"
		else					# 4.2
			echo "-UUSG -DBSD -DBSD4_2"
			host=`hostname`
		fi
		case $host in
		gatech | \
		gt-nimbus | nimbus | \
		gt-cirrus | cirrus | \
		gt-stratus | stratus)	echo -DGITVAX
				;;
		
		*)	echo -UGITVAX
			;;
		esac
		echo -US5R2
	else			# ATT unix
		echo "-DUSG -UBSD -UBSD4_2"
		if grep LOBLK /usr/include/sys/termio.h > /dev/null
		then
			echo -DS5R2
		else
			echo -US5R2
		fi
		echo -UGITVAX
	fi
fi
