#! /bin/sh
# 
# $Header: where,v 1.2 86/07/11 15:14:10 osadr Exp $
# 
# $Log:	where,v $
# Revision 1.2  86/07/11  15:14:10  osadr
# Removed Georgia Tech specific items.
# 
# Revision 1.1  86/05/06  13:34:27  osadr
# Initial revision
# 
# 
# 

# where --- shell file to determine what kind of environment we are in

if test -r /bin/universe	# on a pyramid
then
	OPATH=$PATH
	PATH=/bin
	case `universe` in	# universe is dumb, looking only at argv[0]
	att)	echo "-DUSG -UBSD -UBSD4_2"
		if grep LOBLK /usr/include/sys/termio.h > /dev/null
		then
			echo -DS5R2
		else
			echo -US5R2
		fi
		;;

	ucb)	echo "-UUSG -DBSD -DBSD4_2 -US5R2"
		;;

	*)	echo unknown operating system! 1>&2
		echo "-UUSG -UBSD -UBSD4_2"	# undefine them all
		echo "-US5R2"
		;;
	esac
	PATH=$OPATH
else		# on something that is not a pyramid
	if grep SIGTSTP /usr/include/signal.h > /dev/null
	then		# berkeley unix
		if test -r /usr/include/whoami.h	# 4.1
		then
			echo "-UUSG -DBSD -UBSD4_2"
		else					# 4.2
			echo "-UUSG -DBSD -DBSD4_2"
		fi
		echo -US5R2
	else			# ATT unix
		echo "-DUSG -UBSD -UBSD4_2"
		if grep LOBLK /usr/include/sys/termio.h > /dev/null
		then
			echo -DS5R2
		else
			echo -US5R2
		fi
	fi
fi
